"""Assemble the Safari extension.

The perception JavaScript has one source of truth --
``src/relaykit/perception/js`` -- because the whole point of that package is
that every engine sees a page the same way. The Chrome engine evaluates those
files over CDP; Safari has no CDP, so its extension has to carry them.

Copying at build time rather than forking is what keeps the two honest: there is
no second copy to drift.

    python scripts/build_safari_extension.py                    # assemble
    python scripts/build_safari_extension.py --convert build/    # + macOS app
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PERCEPTION_JS = ROOT / "src" / "relaykit" / "perception" / "js"
EXTENSION = ROOT / "extensions" / "safari"
VENDOR = EXTENSION / "vendor"

#: Copied verbatim. `deep-dom-helpers.js` defines the `deepDom` global the
#: others use, so it must load first -- the manifest lists it first for that
#: reason.
VERBATIM = ("deep-dom-helpers.js",)

#: Wrapped, because the Chrome engine passes these to `Runtime.evaluate` as bare
#: arrow functions. A content script cannot evaluate a string, so each becomes a
#: named function on one shared global instead.
WRAPPED = {"collect-elements.js": "collect", "read.js": "read"}

BANNER = "// GENERATED by scripts/build_safari_extension.py — edit the source in\n"
BANNER += "// src/relaykit/perception/js/ instead.\n\n"


def build() -> int:
    if not PERCEPTION_JS.is_dir():
        print(f"no perception scripts at {PERCEPTION_JS}", file=sys.stderr)
        return 1
    VENDOR.mkdir(parents=True, exist_ok=True)

    for name in VERBATIM:
        source = PERCEPTION_JS / name
        # Strip the helpers placeholder: in the extension the helpers are a
        # separate file loaded first, not inlined per script.
        (VENDOR / name).write_text(BANNER + source.read_text())
        print(f"vendored {name}")

    parts = [BANNER, "window.__relaykitPerception = (() => {\n"]
    for name, export in WRAPPED.items():
        body = (PERCEPTION_JS / name).read_text()
        # The source files are `(arg) => { ... }` expressions with a placeholder
        # where the helpers would be inlined. Here the helpers are already a
        # global, so the placeholder becomes nothing.
        body = body.replace("__RELAYKIT_DEEP_DOM_HELPERS__", "")
        parts.append(f"  const {export} = {body.strip()};\n")
    exports = ", ".join(WRAPPED.values())
    parts.append(f"  return {{ {exports} }};\n}})();\n")
    (EXTENSION / "perception.js").write_text("".join(parts))
    print("built perception.js")

    for required in ("manifest.json", "background.html", "background.js", "content.js"):
        if not (EXTENSION / required).exists():
            print(f"missing {required}", file=sys.stderr)
            return 1
    return 0


def convert(
    out_dir: Path,
    *,
    app_name: str = "RelayKit Bridge",
    bundle_id: str = "dev.relaykit.bridge",
    build_app: bool = True,
) -> int:
    """Turn the extension into a macOS app with Apple's converter, and build it.

    Two things here are not guessable and cost a build each:

    ``safari-web-extension-converter`` derives the *app's* bundle identifier
    from the app name, while taking the *extension's* from
    ``--bundle-identifier``. Left alone the two do not nest, and Xcode refuses
    with "Embedded binary's bundle identifier is not prefixed with the parent
    app's". So the app id is overridden at build time to match.

    Safari also rejects ``"persistent": true`` as an unknown manifest key. The
    background *page* is the part that matters -- Safari terminates a Manifest
    V3 service worker before async callbacks resolve, which kills the socket to
    the engine mid-conversation -- and Safari does honour a background page.
    """
    out_dir = Path(out_dir).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            "xcrun",
            "safari-web-extension-converter",
            str(EXTENSION),
            "--project-location",
            str(out_dir),
            "--app-name",
            app_name,
            "--bundle-identifier",
            bundle_id,
            "--macos-only",
            "--no-open",
            "--no-prompt",
            "--force",
        ],
        check=True,
    )
    if not build_app:
        return 0
    project = out_dir / app_name / f"{app_name}.xcodeproj"
    subprocess.run(
        [
            "xcodebuild",
            "-project",
            str(project),
            "-scheme",
            app_name,
            "-configuration",
            "Release",
            "CODE_SIGN_IDENTITY=-",
            "CODE_SIGN_STYLE=Manual",
            "DEVELOPMENT_TEAM=",
            f"PRODUCT_BUNDLE_IDENTIFIER={bundle_id}",
            "build",
        ],
        check=True,
        capture_output=True,
    )
    print(f"built {app_name}.app -- open it once, then enable it in Safari settings")
    return 0


if __name__ == "__main__":
    code = build()
    if code == 0 and "--convert" in sys.argv:
        target = Path(sys.argv[sys.argv.index("--convert") + 1])
        code = convert(target)
    raise SystemExit(code)
