// GENERATED by scripts/build_safari_extension.py — edit the source in
// src/relaykit/perception/js/ instead.

window.__relaykitPerception = (() => {
  const collect = // Collect interactive elements, across shadow roots and same-process iframes,
// in viewport CSS pixels.
//
// Perception quality is most of what decides how well an agent runs, and this
// is where it lives. Two rules here are not obvious and are both deliberate:
//
//   * A file input is kept even though it fails every visibility test. On real
//     upload flows it is display:none behind a styled button, and dropping it
//     makes uploads impossible on the sites people actually automate.
//   * Coordinates are mapped through the iframe chain. An element's own rect is
//     relative to its own document; the engine clicks in the top-level
//     viewport, and the difference is silent and wrong.

(options) => {


  const opts = options || {};
  const limit = Number(opts.limit || 500);
  const store = (window.__relaykit = window.__relaykit || {});
  store.nodes = [];

  const view = {
    width: window.innerWidth,
    height: window.innerHeight,
    scrollX: window.scrollX,
    scrollY: window.scrollY,
    dpr: window.devicePixelRatio || 1,
  };

  const INTERACTIVE = [
    'a[href]', 'button', 'input', 'select', 'textarea', 'summary', 'label[for]',
    '[role=button]', '[role=link]', '[role=checkbox]', '[role=radio]',
    '[role=tab]', '[role=menuitem]', '[role=option]', '[role=switch]',
    '[role=combobox]', '[role=searchbox]', '[role=textbox]', '[role=slider]',
    '[contenteditable=""]', '[contenteditable="true"]',
    '[onclick]', '[tabindex]:not([tabindex="-1"])',
  ].join(',');

  const isFileInput = (el) =>
    el.tagName === 'INPUT' && (el.getAttribute('type') || '').toLowerCase() === 'file';

  const labelFor = (el) => {
    try {
      const aria = el.getAttribute('aria-label');
      if (aria && aria.trim()) return aria.trim();
      const labelledBy = el.getAttribute('aria-labelledby');
      if (labelledBy) {
        const target = document.getElementById(labelledBy);
        if (target && target.textContent.trim()) return target.textContent.trim();
      }
      if (el.labels && el.labels.length && el.labels[0].textContent.trim()) {
        return el.labels[0].textContent.trim();
      }
      const title = el.getAttribute('title');
      if (title && title.trim()) return title.trim();
      const alt = el.getAttribute('alt');
      if (alt && alt.trim()) return alt.trim();
      const text = (el.innerText || el.textContent || '').trim();
      if (text) return text.slice(0, 160);
      const placeholder = el.getAttribute('placeholder');
      if (placeholder) return placeholder.trim();
      const name = el.getAttribute('name');
      if (name) return name.trim();
    } catch (_) {}
    return '';
  };

  const visible = (el, rect) => {
    if (isFileInput(el)) return true;
    if (!rect || rect.width <= 0 || rect.height <= 0) return false;
    let style;
    try { style = getComputedStyle(el); } catch (_) { return false; }
    if (!style) return false;
    if (style.visibility === 'hidden' || style.display === 'none') return false;
    if (parseFloat(style.opacity || '1') < 0.05) return false;
    // Off-viewport is kept only if it is scrollable into view; fully detached
    // geometry (the classic -9999px hiding trick) is not.
    if (rect.right < -2000 || rect.bottom < -2000) return false;
    return true;
  };

  const attributesOf = (el) => {
    const out = {};
    try {
      for (const attr of el.attributes) {
        if (attr.name === 'style') continue;
        if (attr.name.startsWith('data-react')) continue;
        out[attr.name] = String(attr.value).slice(0, 240);
      }
    } catch (_) {}
    return out;
  };

  const elements = [];
  let roots;
  try {
    roots = deepDom.collectRoots ? deepDom.collectRoots() : [document];
  } catch (_) {
    roots = [document];
  }

  const seen = new Set();
  for (const root of roots) {
    let found;
    try {
      found = root.querySelectorAll(INTERACTIVE);
    } catch (_) {
      continue;
    }
    for (const el of found) {
      if (elements.length >= limit) break;
      if (seen.has(el)) continue;
      seen.add(el);

      let rect;
      try {
        rect = deepDom.getTopViewportRect(el) || el.getBoundingClientRect();
      } catch (_) {
        continue;
      }
      if (!visible(el, rect)) continue;

      const index = store.nodes.push(el) - 1;
      let value = '';
      try { value = 'value' in el ? String(el.value ?? '') : ''; } catch (_) {}

      elements.push({
        index,
        x: rect.x ?? rect.left,
        y: rect.y ?? rect.top,
        width: rect.width,
        height: rect.height,
        tag: el.tagName.toLowerCase(),
        role: el.getAttribute('role') || '',
        label: labelFor(el),
        value,
        placeholder: el.getAttribute('placeholder') || '',
        editable: !!el.isContentEditable ||
          ['INPUT', 'TEXTAREA', 'SELECT'].includes(el.tagName),
        disabled: !!el.disabled,
        frameId: '',
        attributes: attributesOf(el),
      });
    }
  }

  let text = '';
  if (opts.includeText) {
    try { text = document.body ? document.body.innerText.slice(0, 20000) : ''; } catch (_) {}
  }

  const signature = elements
    .map((e) => `${e.tag}:${Math.round(e.x)},${Math.round(e.y)}:${e.value}`)
    .join('|');

  return {
    viewport: view,
    elements,
    text,
    signature: String(signature.length) + ':' + signature.slice(0, 2000),
  };
};
  const read = // Small reads and writes against the node registry the collector filled.
// One entry point with an `op` switch: every call is a round trip, and the
// registry has to be shared with the collector for handles to stay addressable.

(request) => {


  const store = (window.__relaykit = window.__relaykit || {});
  const nodes = store.nodes || [];
  const node = (i) => nodes[i] || null;

  switch (request.op) {
    case 'viewport': {
      // maxScroll* lets a caller answer "can this page scroll further?" without
      // dispatching a wheel event to find out. That matters more than it looks:
      // a wheel at the scroll limit may never be acknowledged by the compositor,
      // and an unacknowledged input command blocks every later command on the
      // same debuggee behind it.
      const doc = document.documentElement;
      const body = document.body;
      const scrollWidth = Math.max(doc ? doc.scrollWidth : 0, body ? body.scrollWidth : 0);
      const scrollHeight = Math.max(doc ? doc.scrollHeight : 0, body ? body.scrollHeight : 0);
      return {
        width: window.innerWidth,
        height: window.innerHeight,
        scrollX: window.scrollX,
        scrollY: window.scrollY,
        dpr: window.devicePixelRatio || 1,
        maxScrollX: Math.max(0, scrollWidth - window.innerWidth),
        maxScrollY: Math.max(0, scrollHeight - window.innerHeight),
      };
    }

    case 'box': {
      const el = node(request.index);
      if (!el || !el.isConnected) return null;
      let rect;
      try {
        rect = deepDom.getTopViewportRect(el) || el.getBoundingClientRect();
      } catch (_) { return null; }
      // A click at a negative y is a click on nothing, so nudge it into view
      // before reporting where it is.
      if (rect.bottom < 0 || rect.top > window.innerHeight) {
        try { el.scrollIntoView({ block: 'center', inline: 'center' }); } catch (_) {}
        try {
          rect = deepDom.getTopViewportRect(el) || el.getBoundingClientRect();
        } catch (_) { return null; }
      }
      return {
        x: rect.x ?? rect.left, y: rect.y ?? rect.top,
        width: rect.width, height: rect.height,
      };
    }

    case 'value': {
      const el = node(request.index);
      if (!el) return null;
      if (el.isContentEditable) return el.textContent || '';
      return 'value' in el ? String(el.value ?? '') : (el.textContent || '');
    }

    case 'activeValue': {
      const el = document.activeElement;
      if (!el) return '';
      if (el.isContentEditable) return el.textContent || '';
      return 'value' in el ? String(el.value ?? '') : (el.textContent || '');
    }

    case 'focus': {
      const el = node(request.index);
      if (!el) return false;
      try { el.focus({ preventScroll: false }); } catch (_) { return false; }
      return document.activeElement === el;
    }

    case 'clear': {
      const el = node(request.index) || document.activeElement;
      if (!el) return false;
      try {
        if (el.isContentEditable) {
          el.textContent = '';
        } else {
          // Assigning .value directly is invisible to React and friends, which
          // track the native setter. Call it explicitly, then fire the events
          // the framework is listening for.
          const proto = el instanceof HTMLTextAreaElement
            ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
          const setter = Object.getOwnPropertyDescriptor(proto, 'value');
          if (setter && setter.set) { setter.set.call(el, ''); } else { el.value = ''; }
        }
        el.dispatchEvent(new Event('input', { bubbles: true }));
        el.dispatchEvent(new Event('change', { bubbles: true }));
      } catch (_) { return false; }
      return true;
    }

    case 'select': {
      const el = node(request.index);
      if (!el || el.tagName !== 'SELECT') return { ok: false, reason: 'not a select' };
      let chosen = null;
      for (let i = 0; i < el.options.length; i += 1) {
        const opt = el.options[i];
        const byValue = request.value && opt.value === request.value;
        const byLabel = request.label &&
          opt.textContent.trim().toLowerCase() === String(request.label).trim().toLowerCase();
        const byIndex = request.optionIndex >= 0 && i === request.optionIndex;
        if (byValue || byLabel || byIndex) { chosen = opt; break; }
      }
      if (!chosen) {
        return {
          ok: false,
          reason: 'no matching option',
          available: Array.from(el.options).map((o) => o.textContent.trim()).slice(0, 20),
        };
      }
      el.value = chosen.value;
      el.dispatchEvent(new Event('input', { bubbles: true }));
      el.dispatchEvent(new Event('change', { bubbles: true }));
      return { ok: true, value: chosen.value, label: chosen.textContent.trim() };
    }

    case 'signature': {
      // Cheap structural fingerprint, used to decide whether an action changed
      // anything. Deliberately not a pixel hash: this survives caret blink and
      // animation, which a pixel hash does not.
      const body = document.body;
      if (!body) return '0';
      let text = '';
      try { text = body.innerText || ''; } catch (_) {}
      const active = document.activeElement;
      const focus = active
        ? active.tagName + ':' + (('value' in active ? active.value : '') ?? '')
        : '';
      return `${document.location.href}|${text.length}|${text.slice(0, 1500)}|${focus}`;
    }

    case 'scrollHeight':
      return document.documentElement.scrollHeight;

    case 'href':
      return document.location.href;

    case 'scrollBy': {
      // Safari has no CDP, so there is no Input.dispatchMouseEvent to send a
      // wheel with. window.scrollBy is not a gesture and will not trigger
      // wheel handlers, but it does move the page, which is what the caller
      // asked for. Container scrolling goes through pointer events instead.
      window.scrollBy(Number(request.x) || 0, Number(request.y) || 0);
      return { scrollX: window.scrollX, scrollY: window.scrollY };
    }

    default:
      return null;
  }
};
  return { collect, read };
})();
